apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "{{ keycloak.server_name }}"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: keycloak-ingress
  namespace: keycloak
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ keycloak.server_name }}"
      http:
        paths:
          - backend:
              service:
                name: keycloak-psc-service
                port:
                  number: 8443
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - "{{ keycloak.server_name }}"
      secretName: keycloak-tls-secret
