---
#
# Role used to upload to synapse the image used by the ProSant√© Connect button
# The registered variable mxc contains the MXC uri of the image. It will be used in later roles
#
- name: PSC connect button image - upload files to synapse and retrieve the MXC uri
  shell:
    "curl --data-binary @roles/psc-button/files/ProSanteConnect_PICTO_COULEURS.png 'https://{{ matrix.server_name }}/_matrix/media/v3/upload?filename=psc_picto.png'   -X 'POST'   -H 'Authorization:
    Bearer {{ admin_access_token }}'   -H 'Content-Type: image/png'   --compressed | jq -r '.content_uri'"
  register: mxc
