# This workflow installs the latest version of Terraform CLI. On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform

name: 'Deployment'

on:
  push:

permissions:
  contents: read

env:
  # configure access to S3 where tfstates are stored
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  # configure access to OVH provider
  OVH_ENDPOINT: ${{ vars.OVH_ENDPOINT }}
  OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
  OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
  OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
  # variables used by infrastructure components
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  CLUSTER_REGION: ${{ vars.CLUSTER_REGION }}
  CLUSTER_VERSION: ${{ vars.CLUSTER_VERSION }}
  NODEPOOL_NAME: ${{ vars.NODEPOOL_NAME }}
  NODEPOOL_FLAVOR: ${{ vars.NODEPOOL_FLAVOR }}

jobs:
  set_environment:
    name: 'Dynamic detection of environment'
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
      - id: setenv
        run: |
          BRANCH=${{ github.ref_name }}
          ENVIRONMENT=$(echo $BRANCH | cut -f1 -d'-')

          case $ENVIRONMENT in
          main)
          echo "my_env=production" >> $GITHUB_OUTPUT
          ;;

          develop)
          echo "my_env=develop" >> $GITHUB_OUTPUT
          ;;

          *)
          echo "other case : environment=${ENVIRONMENT}"
          echo "my_env=${ENVIRONMENT}" >> $GITHUB_OUTPUT

          esac

  provisioning:
    name: 'Provisioning with Terraform'
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set_environment.outputs.my_env }}
    needs: set_environment

    # Use the Bash shell
    defaults:
      run:
        shell: bash

    steps:
      - name: Environment used
        run: echo "${{ needs.set_environment.outputs.my_env }}"

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init -backend-config="bucket=terraform-states-hp-${{ needs.set_environment.outputs.my_env }}"

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generates a terraform.tfvars file from the environment variables
      - name: Generate tfvars file
        run: sh scripts/generate_tfvars_file.sh

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false

        # On push to "main", build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud".
        # See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        # if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false


  configuration:
    name: 'Configuration of Kubernetes cluster'
    runs-on: ubuntu-latest
    needs: [provisioning, set_environment]
    environment:
      name: ${{ needs.set_environment.outputs.my_env }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Environment used
        run: echo "${{ needs.set_environment.outputs.my_env }}"

      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI but without wrapper
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=terraform-states-hp-${{ needs.set_environment.outputs.my_env }}"

      # Generate kubeconfig file
      - name: Generate kubeconfig file
        run: sh scripts/generate_kubeconfig_file.sh

      # Run ansible_configuration.sh script
      - name: ansible_configuration script
        run: sh scripts/ansible_configuration.sh
