name: Linters

on:
  workflow_dispatch:
  push:

jobs:
  lint-terraform:
    name: "Terraform linter"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.7

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Validate
        run: ">&2 terraform fmt --check"

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.48.0

      - name: Run TFLint
        run: tflint -f compact

  lint-yaml:
    name: "Yaml linter"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3
